name: Compile-python

on: [push]

jobs:
  build-python:
      runs-on: ubuntu-latest
      container: ghcr.io/fix-project/wasm_toolchain_docker:latest
      steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
        with:
          submodules: 'true'
      - shell: bash
        run: 'echo HOME=/home | sudo tee -a $GITHUB_ENV'
      - name: "Build python"
        shell: bash
        run: |
          cd python/
          chmod +x build-python-wasi.sh
          ./build-python-wasi.sh
      - name: "Upload WASI artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: wasi-3.11
          path: |
            python/cpython/builddir/wasi/LICENSE
            python/cpython/builddir/wasi/commit.txt
            python/cpython/builddir/wasi/python.wasm
            python/cpython/builddir/wasi/pybuilddir.txt
            python/cpython/builddir/wasi/build/lib.wasi-wasm32-3.*/_sysconfigdata__wasi_wasm32-wasi.py
            python/cpython/builddir/wasi/Lib/
          if-no-files-found: error
  build-wabt:
      runs-on: ubuntu-latest
      container: ghcr.io/fix-project/wasm_toolchain_docker:latest
      steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
        with:
          submodules: 'true'
      - shell: bash
        run: 'echo HOME=/home | sudo tee -a $GITHUB_ENV'
      - name: "Build wabt"
        shell: bash
        run: |
          cd wabt-tools
          chmod +x build-wabt-wasi.sh
          ./build-wabt-wasi.sh
      - name: "Upload WASI artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: wabt-wasi
          path: |
            wabt-tools/wabt/build/
          if-no-files-found: error
  build-clang:
      runs-on: ubuntu-latest
      container: ghcr.io/fix-project/wasm_toolchain_docker:latest
      steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
        with:
          submodules: 'true'
      - shell: bash
        run: 'echo HOME=/home | sudo tee -a $GITHUB_ENV'
      - name: "Build clang"
        shell: bash
        run: |
          cd clang-port
          chmod +x build-clang-wasi.sh
          ./build-clang-wasi.sh
      - name: "Upload WASI artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: clang-wasi
          path: |
            clang-port/llvm-project/build/
          if-no-files-found: error
